name: 'My personal labeler'
description: 'Add labels to new pull requests based on the files that are changed'
author: 'fluzzi'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
runs:
  using: 'node12'
  main: 'lib/main.js'
